- name: Configure webserver with nginx and tls
  hosts: all
  become: yes
  tasks:
    - name: Install nginx
      apt:
        name: nginx
        update_cache: yes
        state: present

    - name: Install nodejs
      apt:
        name: nodejs
        update_cache: yes
        state: present

    - name: Install npm
      apt:
        name: npm
        update_cache: yes
        state: present

    - name: Install pm2
      npm:
        name: pm2
        global: yes

    - name: Configure NGINX server
      copy:
        content: "server {\
                    listen       80;\
                    server_name  localhost;\
                    location /api {\
                        proxy_pass http://localhost:3000/;\
                    }\
                }"
        dest: "/etc/nginx/conf.d/default.conf"

    - name: start nginx
      command: 'service nginx start'

    - name: restart nginx
      command: 'nginx -s reload'

    - name: start pm2 nodejs app
      command: 'pm2 start /vagrant/hello.js'
