Vagrant.configure("2") do |config|
  config.vm.box = "debian/buster64"
  config.vm.provider "virtualbox" do |vb|
    vb.name = "Vagrantfile_TP4"
    vb.cpus = 2
    vb.memory = 2048
  end
  config.vm.network "forwarded_port", guest: 80, host: 3000
  config.vm.provision "ansible_local" do |ansible|
    ansible.verbose = "v"
    ansible.playbook = "playbook.yml"
  end
end
